# Global configuration and hyperparameters

GRID_WIDTH = 30
GRID_HEIGHT = 30
OBSTACLE_DENSITY = 0.1
USE_HEIGHT_MAP = True
OBSTACLE_COUNT = 4  # Dynamic obstacles

START = (0, 0)
GOAL = (GRID_WIDTH - 1, GRID_HEIGHT - 1)

# Genetic Algorithm params
MAX_STEPS_GA = (GRID_WIDTH + GRID_HEIGHT) * 2  # 120
POPULATION_SIZE = 50
GENERATIONS = 100
MUTATION_RATE = 0.02

# Simulated Annealing params
MAX_STEPS_SA = (GRID_WIDTH + GRID_HEIGHT) * 4  # 120
TEMPERATURE = 100.0
COOLING_RATE = 0.995
MIN_TEMPERATURE = 0.1

# Sparrow Search Algorithm params
SSA_POP_SIZE = 100
SSA_ITERATIONS = 200
MAX_STEPS_SSA = (GRID_WIDTH + GRID_HEIGHT) * 4  # 240